import psycopg2

from sources.FullDB.text_full import text_par
from sources.postgres import config
from sources.search.search import extract_features

songs = [
    "... Baby One More Time.mp3",
    "1999.mp3",
    "9 U2 - Where The Streets Have No Name - Drum Cover.mp3",
    "ABBA - Dancing Queen (Official Lyric Video).mp3",
    "AC⧸DC - Back In Black.mp3",
    "AC⧸DC - Highway to Hell [Audio].mp3",
    "Adele - Rolling In The Deep.mp3",
    "Adele - Someone Like You.mp3",
    "Alright.mp3",
    "Annie Lennox - Walking on Broken Glass (Official Video).mp3",
    "Aretha Franklin - (You Make Me Feel Like) A Natural Woman (Official Audio).mp3",
    "Aretha Franklin - Chain of Fools (Official Lyric Video).mp3",
    "Aretha Franklin - I Never Loved a Man (The Way I Love You) (Official Audio).mp3",
    "Aretha Franklin - Respect (Official Audio).mp3",
    "Aretha Franklin - Think (Official Audio).mp3",
    "B.O.B. (Bombs Over Baghdad).mp3",
    "Beat It.mp3",
    "Beyoncé - Crazy In Love (Official Audio) ft. JAY-Z.mp3",
    "Billie Jean.mp3",
    "Black or White.mp3",
    "Blue Suede Shoes.mp3",
    "Bob Dylan - Blowin' in the Wind (Official Audio).mp3",
    "Bob Dylan - Knockin' On Heaven's Door (Official Audio).mp3",
    "Bob Dylan - Like a Rolling Stone (Official Audio).mp3",
    "Bob Dylan - Mr. Tambourine Man (Official Audio).mp3",
    "Bob Dylan - The Times They Are A-Changin' (Official Audio).mp3",
    "bob-marley-the-wailers-three-little-birds.mp3",
    "Bon Jovi - Bed Of Roses (Official Music Video).mp3",
    "Bon Jovi - It's My Life HD HQ AUDIO.mp3",
    "Bon Jovi - Livin' On A Prayer.mp3",
    "Bon Jovi - Wanted Dead Or Alive.mp3",
    "Bon Jovi - You Give Love A Bad Name.mp3",
    "Born To Be Wild.mp3",
    "Breaking the Habit.mp3",
    "Britney Spears - (You Drive Me) Crazy (Audio).mp3",
    "Cardi B - Bodak Yellow [OFFICIAL MUSIC VIDEO].mp3",
    "Cardi B - Money (Official Audio).mp3",
    "Cardi B - Up [Official Audio].mp3",
    "Cardi B - WAP feat. Megan Thee Stallion [Official Audio].mp3",
    "Cardi B, Bad Bunny & J Balvin - I Like It [Official Audio].mp3",
    "Champagne Supernova (Remastered).mp3",
    "Clair de Lune (Studio Version).mp3",
    "Come as You Are - Nirvana.mp3",
    "Comedoz - Ямайка.mp3",
    "Crawling.mp3",
    "Crazy Little Thing Called Love (Remastered 2011).mp3",
    "Cry Wolf (2016 Remaster).mp3",
    "Cyndi Lauper - All Through the Night (Audio).mp3",
    "Cyndi Lauper - She Bop.mp3",
    "Cyndi Lauper - Time After Time (Audio).mp3",
    "Cyndi Lauper - True Colors (Official Lyric Video).mp3",
    "Dave Brubeck, The Dave Brubeck Quartet - Take Five (Audio).mp3",
    "DNA - Kendrick Lamar (AUDIO).mp3",
    "Don't Look Back In Anger (Remastered).mp3",
    "Don't Stand So Close To Me.mp3",
    "Drake - Hotline Bling (Official Audio).mp3",
    "Ed Sheeran - Perfect [Official Lyric Video].mp3",
    "Ed Sheeran - Thinking Out Loud [Official Audio].mp3",
    "Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
    "Elvis Presley - Hound Dog (Official Audio).mp3",
    "Elvis Presley - Jailhouse Rock (Official Audio).mp3",
    "Elvis Presley - Suspicious Minds (Official Audio).mp3",
    "Eminem - Without Me (Audio).mp3",
    "Eminem Feat Dido - Stan (Audio).mp3",
    "Enjoy the Silence.mp3",
    "Enter Sandman (Remastered).mp3",
    "Every Breath You Take.mp3",
    "Eye of the Tiger.mp3",
    "Footloose.mp3",
    "Four Seasons ~ Vivaldi.mp3",
    "Für Elise.mp3",
    "Georgia on My Mind.mp3",
    "Girls Just Want to Have Fun.mp3",
    "God's Plan.mp3",
    "Good Vibrations.mp3",
    "Guns N' Roses - Sweet Child O' Mine (Official Audio HQ).mp3",
    "Gymnopédie No. 1.mp3",
    "Habanera (by Bizet).mp3",
    "Here Comes the Rain Again (2018 Remastered).mp3",
    "Hey Jude (Remastered 2015).mp3",
    "Hey Ya! - OutKast - Official Audio HD.mp3",
    "Hotel California (2013 Remaster).mp3",
    "HUMBLE..mp3",
    "Hunting High and Low (2015 Remaster).mp3",
    "I Wanna Dance with Somebody (Who Loves Me).mp3",
    "I Want To Break Free (Remastered 2011).mp3",
    "In My Feelings.mp3",
    "In the End.mp3",
    "John Lennon - Imagine (Remastered 2020).mp3",
    "Johnny Be Goode.mp3",
    "Journey - Don't Stop Believin' (Official Audio).mp3",
    "Katrina & The Waves - Walking On Sunshine.mp3",
    "Kendrick Lamar - King Kunta.mp3",
    "La Isla Bonita.mp3",
    "Led Zeppelin - Stairway To Heaven (Official Audio).mp3",
    "Led Zeppelin - Whole Lotta Love (Official Audio).mp3",
    "Leonard Cohen - Hallelujah (Audio).mp3",
    "Like a Prayer.mp3",
    "Linkin Park - Somewhere I Belong (Audio).mp3",
    "Little Red Corvette (2019 Remaster).mp3",
    "Live Forever (Remastered).mp3",
    "Lose Yourself (From ＂8 Mile＂ Soundtrack).mp3",
    "Lynyrd Skynyrd - Free Bird (Official Audio).mp3",
    "Man in the Mirror.mp3",
    "Mark Ronson - Uptown Funk (Official Audio) ft. Bruno Mars.mp3",
    "Marvin Gaye - What's Going On.mp3",
    "Material Girl.mp3",
    "Maurice Ravel - Bolero.mp3",
    "Message In A Bottle.mp3",
    "Michael Jackson Smooth Criminal (Audio HQ).mp3",
    "Miles Davis - All Blues (Official Audio).mp3",
    "Miles Davis - Blue In Green (Official Audio).mp3",
    "Miles Davis - Freddie Freeloader (Official Audio).mp3",
    "Miles Davis - So What (Official Audio).mp3",
    "Moonlight Sonata.mp3",
    "Mr. Brightside.mp3",
    "Ms. Jackson.mp3",
    "New Order - Blue Monday (Official Lyric Video).mp3",
    "Nice For What.mp3",
    "Nirvana - Heart-Shaped Box.mp3",
    "Nirvana - In Bloom.mp3",
    "Nirvana - Lithium [Nevermind] [HQ Sound].mp3",
    "No Woman, No Cry (1974) - Bob Marley & The Wailers.mp3",
    "Numb.mp3",
    "Ode to Joy.mp3",
    "One Dance (feat. WizKid & Kyla) - Drake (Official Audio).mp3",
    "One.mp3",
    "Oops!... I Did It Again.mp3",
    "Outkast - Roses.mp3",
    "Papa Don't Preach.mp3",
    "Personal Jesus.mp3",
    "Pharrell Williams - Happy (Official Audio).mp3",
    "Pride (In The Name Of Love).mp3",
    "Prince & The Revolution - Kiss (Official Music Video).mp3",
    "Puccini - Turandot： Nessun Dorma [HQ].mp3",
    "Purple Rain.mp3",
    "Queen - Another One Bites The Dust (Official Lyric Video).mp3",
    "Queen - Don't Stop Me Now (Official Lyric Video).mp3",
    "Queen - Killer Queen (Official Lyric Video).mp3",
    "Queen - Radio Ga Ga (Official Lyric Video).mp3",
    "Queen - Somebody To Love (Official Lyric Video).mp3",
    "Queen - We Will Rock You (Official Video).mp3",
    "Queen – Bohemian Rhapsody (Official Video Remastered).mp3",
    "QUEEN： We Are The Champions (HQ).mp3",
    "Ray Charles - Hallelujah I Love Her So (Live) (Official Audio).mp3",
    "Ray Charles - Hit The Road Jack (Official Lyrics Video).mp3",
    "Ray Charles - I got a woman.mp3",
    "Ray Charles - What'd I Say (Official Audio).mp3",
    "Red Hot Chili Peppers - Californication (Highest Quality).mp3",
    "Red Hot Chili Peppers - Otherside - Remastered.mp3",
    "Red Hot Chili Peppers - Scar Tissue (Highest Quality).mp3",
    "Red Hot Chili Peppers - Under The Bridge - Remastered.mp3",
    "RED HOT CHILLI PEPPERS - CAN'T STOP.mp3",
    "Ride of the Valkyries.mp3",
    "Sex Pistols - God Save The Queen.mp3",
    "Shallow (Radio Edit).mp3",
    "So Fresh, So Clean Outkast.mp3",
    "Soft Cell - Tainted Love (Official Music Video).mp3",
    "Stay on These Roads (2016 Remaster).mp3",
    "Sunday Bloody Sunday.mp3",
    "Sweet Dreams (Are Made of This) (2005 Remaster).mp3",
    "Take Me Out.mp3",
    "Take on Me.mp3",
    "The Blacker The Berry.mp3",
    "The Dandy Warhols - Bohemian Like You.mp3",
    "The Masterplan (Remastered).mp3",
    "The Police - Roxanne (HQ).mp3",
    "The Real Slim Shady.mp3",
    "The Show Must Go On (Remastered 2011).mp3",
    "The Strokes - Juicebox (Official HD Video).mp3",
    "The Strokes - Last Nite (Official Audio).mp3",
    "The Strokes - Reptilia (Official HD Video).mp3",
    "The Sun Always Shines on TV (2016 Remaster).mp3",
    "The Weeknd - Blinding Lights (Official Audio).mp3",
    "The White Stripes - Seven Nation Army (Audio).mp3",
    "There Must Be An Angel (Playing With My Heart) (Remastered).mp3",
    "Thriller.mp3",
    "Till I Collapse.mp3",
    "Toxic.mp3",
    "U2 - With Or Without You (Official Music Video).mp3",
    "Walking On The Moon.mp3",
    "When Doves Cry.mp3",
    "Whitney Houston - I Will Always Love You (Official Audio).mp3",
    "Womanizer.mp3",
    "Wonderwall (Remastered).mp3",
    "Would I Lie to You？ (Remastered Version).mp3",
    "Yesterday (Remastered 2015).mp3",
    "«Король и Шут» - «Кукла Колдуна» HD.mp3.mp3",
    "ДДТ - Что такое осень (Official video).mp3.mp3",
    "Король и Шут - Кукла Колдуна.mp3.mp3",
    "Олег Газманов #Морячка# (1991).mp3.mp3",
    "Олег газманов есаул дескотека 80.mp3 — копия.mp3",
    "Олег газманов есаул дескотека 80.mp3.mp3",
    "Олег_газманов_есаул_дескотека_80_mp3_—_копия.mp3"
]

songs_with_info = [
    ("... Baby One More Time", "Britney Spears", "...Baby One More Time", 1999, ["Pop"]),
    ("1999", "Prince", "1999", 1982, ["Funk", "Pop", "Electronic"]),
    ("Where The Streets Have No Name", "U2", "The Joshua Tree", 1987, ["Rock"]),
    ("Dancing Queen", "ABBA", "Arrival", 1976, ["Pop"]),
    ("Back In Black", "AC/DC", "Back in Black", 1980, ["Rock", "Hard Rock"]),
    ("Highway to Hell", "AC/DC", "Highway to Hell", 1979, ["Rock", "Hard Rock"]),
    ("Rolling In The Deep", "Adele", "21", 2010, ["Pop", "Soul"]),
    ("Someone Like You", "Adele", "21", 2011, ["Pop", "Soul"]),
    ("Alright", "Kendrick Lamar", "To Pimp a Butterfly", 2015, ["Hip Hop", "Jazz Rap"]),
    ("Walking on Broken Glass", "Annie Lennox", "Medusa", 1995, ["Pop"]),
    ("(You Make Me Feel Like) A Natural Woman", "Aretha Franklin", "Lady Soul", 1968, ["Soul", "R&B"]),
    ("Chain of Fools", "Aretha Franklin", "Lady Soul", 1967, ["Soul", "R&B"]),
    ("I Never Loved a Man (The Way I Love You)", "Aretha Franklin", "I Never Loved a Man the Way I Love You", 1967, ["Soul", "R&B"]),
    ("Respect", "Aretha Franklin", "Respect", 1967, ["Soul", "R&B"]),
    ("Think", "Aretha Franklin", "Aretha Now", 1968, ["Soul", "R&B"]),
    ("B.O.B. (Bombs Over Baghdad)", "Outkast", "Stankonia", 2000, ["Hip Hop", "Funk", "Drum and Bass"]),
    ("Beat It", "Michael Jackson", "Thriller", 1982, ["Pop", "Rock", "Funk"]),
    ("Crazy In Love", "Beyoncé ft. Jay-Z", "Dangerously in Love", 2003, ["R&B", "Pop", "Hip Hop"]),
    ("Billie Jean", "Michael Jackson", "Thriller", 1982, ["Pop", "R&B"]),
    ("Black or White", "Michael Jackson", "Dangerous", 1991, ["Pop", "Rock", "R&B"]),
    ("Blue Suede Shoes", "Carl Perkins", "Dance Album of Carl Perkins", 1957, ["Rock and Roll", "Rockabilly"]),
    ("Blowin' in the Wind", "Bob Dylan", "The Freewheelin' Bob Dylan", 1963, ["Folk"]),
    ("Knockin' On Heaven's Door", "Bob Dylan", "Pat Garrett and Billy the Kid", 1973, ["Folk", "Rock"]),
    ("Like a Rolling Stone", "Bob Dylan", "Highway 61 Revisited", 1965, ["Rock", "Folk"]),
    ("Mr. Tambourine Man", "Bob Dylan", "Bringing It All Back Home", 1965, ["Folk", "Rock"]),
    ("The Times They Are A-Changin'", "Bob Dylan", "The Times They Are A-Changin'", 1964, ["Folk"]),
    ("Three Little Birds", "Bob Marley & The Wailers", "Exodus", 1977, ["Reggae"]),
    ("Bed Of Roses", "Bon Jovi", "Keep the Faith", 1992, ["Rock", "Soft Rock"]),
    ("It's My Life", "Bon Jovi", "Crush", 2000, ["Rock", "Pop Rock"]),
    ("Livin' On A Prayer", "Bon Jovi", "Slippery When Wet", 1986, ["Rock", "Hard Rock"]),
    ("Wanted Dead Or Alive", "Bon Jovi", "Slippery When Wet", 1986, ["Rock", "Hard Rock"]),
    ("You Give Love A Bad Name", "Bon Jovi", "Slippery When Wet", 1986, ["Rock", "Hard Rock"]),
    ("Born To Be Wild", "Steppenwolf", "Steppenwolf", 1968, ["Rock", "Hard Rock"]),
    ("Breaking the Habit", "Linkin Park", "Meteora", 2003, ["Rock", "Alternative Rock", "Nu Metal"]),
    ("(You Drive Me) Crazy", "Britney Spears", "...Baby One More Time", 1999, ["Pop"]),
    ("Bodak Yellow", "Cardi B", "Invasion of Privacy", 2017, ["Hip Hop", "Trap"]),
    ("Money", "Cardi B", "Invasion of Privacy", 2018, ["Hip Hop", "Trap"]),
    ("Up", "Cardi B", "Single", 2021, ["Hip Hop", "Trap"]),
    ("WAP", "Cardi B ft. Megan Thee Stallion", "Single", 2020, ["Hip Hop", "Trap"]),
    ("I Like It", "Cardi B, Bad Bunny & J Balvin", "Invasion of Privacy", 2018, ["Hip Hop", "Latin Trap"]),
    ("Champagne Supernova", "Oasis", "(What's the Story) Morning Glory?", 1995, ["Rock", "Britpop"]),
    ("Clair de Lune", "Claude Debussy", "Suite bergamasque", 1905, ["Classical", "Impressionism"]),
    ("Come as You Are", "Nirvana", "Nevermind", 1991, ["Rock", "Grunge"]),
    ("Ямайка", "Comedoz", "Single", 2020, ["Pop", "Dance"]),
    ("Crawling", "Linkin Park", "Hybrid Theory", 2000, ["Rock", "Alternative Rock", "Nu Metal"]),
    ("Crazy Little Thing Called Love", "Queen", "The Game", 1979, ["Rock and Roll", "Pop"]),
    ("Cry Wolf", "a-ha", "Scoundrel Days", 1986, ["Synth-pop"]),
    ("All Through the Night", "Cyndi Lauper", "She's So Unusual", 1983, ["Pop"]),
    ("She Bop", "Cyndi Lauper", "She's So Unusual", 1983, ["Pop", "New Wave"]),
    ("Time After Time", "Cyndi Lauper", "She's So Unusual", 1983, ["Pop", "Synth-pop"]),
    ("True Colors", "Cyndi Lauper", "True Colors", 1986, ["Pop"]),
    ("Take Five", "The Dave Brubeck Quartet", "Time Out", 1959, ["Jazz"]),
    ("DNA", "Kendrick Lamar", "DAMN.", 2017, ["Hip Hop", "Rap"]),
    ("Don't Look Back In Anger", "Oasis", "(What's the Story) Morning Glory?", 1995, ["Rock", "Britpop"]),
    ("Don't Stand So Close To Me", "The Police", "Zenyatta Mondatta", 1980, ["Rock", "New Wave"]),
    ("Hotline Bling", "Drake", "Views", 2015, ["Hip Hop", "R&B"]),
    ("Perfect", "Ed Sheeran", "÷", 2017, ["Pop"]),
    ("Thinking Out Loud", "Ed Sheeran", "x", 2014, ["Pop", "Soul"]),
    ("Can't Help Falling In Love", "Elvis Presley", "Blue Hawaii", 1961, ["Pop", "Rock and Roll"]),
    ("Hound Dog", "Elvis Presley", "Elvis Presley", 1956, ["Rock and Roll", "Blues"]),
    ("Jailhouse Rock", "Elvis Presley", "Elvis' Golden Records", 1958, ["Rock and Roll"]),
    ("Suspicious Minds", "Elvis Presley", "From Elvis in Memphis", 1969, ["Rock and Roll", "Pop", "Soul"]),
    ("Without Me", "Eminem", "The Eminem Show", 2002, ["Hip Hop"]),
    ("Stan", "Eminem ft. Dido", "The Marshall Mathers LP", 2000, ["Hip Hop"]),
    ("Enjoy the Silence", "Depeche Mode", "Violator", 1990, ["Synth-pop", "Electronic"]),
    ("Enter Sandman", "Metallica", "Metallica", 1991, ["Metal"]),
    ("Every Breath You Take", "The Police", "Synchronicity", 1983, ["Pop", "Rock"]),
    ("Eye of the Tiger", "Survivor", "Rocky III", 1982, ["Rock", "Hard Rock"]),
    ("Footloose", "Kenny Loggins", "Footloose", 1984, ["Pop", "Rock"]),
    ("Four Seasons", "Antonio Vivaldi", "Le quattro stagioni", 1725, ["Classical", "Baroque"]),
    ("Für Elise", "Ludwig van Beethoven", "Bagatelle No. 25 in A minor", 1810, ["Classical"]),
    ("Georgia on My Mind", "Ray Charles", "The Genius of Ray Charles", 1959, ["Jazz", "Soul"]),
    ("Girls Just Want to Have Fun", "Cyndi Lauper", "She's So Unusual", 1983, ["Pop", "New Wave"]),
    ("God's Plan", "Drake", "Scorpion", 2018, ["Hip Hop", "Trap"]),
    ("Good Vibrations", "The Beach Boys", "Smiley Smile", 1967, ["Pop", "Rock"]),
    ("Sweet Child O' Mine", "Guns N' Roses", "Appetite for Destruction", 1987, ["Rock", "Hard Rock"]),
    ("Gymnopédie No. 1", "Erik Satie", "Gymnopédies", 1888, ["Classical", "Ambient"]),
    ("Habanera", "Georges Bizet", "Carmen", 1875, ["Classical", "Opera"]),
    ("Here Comes the Rain Again", "Eurythmics", "Touch", 1983, ["Synth-pop"]),
    ("Hey Jude", "The Beatles", "Hey Jude", 1968, ["Rock", "Pop"]),
    ("Hey Ya!", "Outkast", "Speakerboxxx/The Love Below", 2003, ["Hip Hop", "Funk", "Pop"]),
    ("Hotel California", "Eagles", "Hotel California", 1976, ["Rock"]),
    ("HUMBLE.", "Kendrick Lamar", "DAMN.", 2017, ["Hip Hop", "Rap"]),
    ("Hunting High and Low", "a-ha", "Hunting High and Low", 1985, ["Synth-pop"]),
    ("I Wanna Dance with Somebody (Who Loves Me)", "Whitney Houston", "Whitney", 1987, ["Pop", "R&B"]),
    ("I Want To Break Free", "Queen", "The Works", 1984, ["Rock", "Pop"]),
    ("In My Feelings", "Drake", "Scoron", 2018, ["Hip Hop", "Pop Rap"]),
    ("In the End", "Linkin Park", "Hybrid Theory", 2000, ["Rock", "Alternative Rock", "Nu Metal"]),
    ("Imagine", "John Lennon", "Imagine", 1971, ["Rock", "Pop"]),
    ("Johnny Be Goode", "Chuck Berry", "Chuck Berry Is on Top", 1959, ["Rock and Roll"]),
    ("Don't Stop Believin'", "Journey", "Escape", 1981, ["Rock"]),
    ("Walking On Sunshine", "Katrina & The Waves", "Walking on Sunshine", 1985, ["Pop", "New Wave"]),
    ("King Kunta", "Kendrick Lamar", "To Pimp a Butterfly", 2015, ["Hip Hop", "Funk"]),
    ("La Isla Bonita", "Madonna", "True Blue", 1986, ["Pop", "Latin Pop"]),
    ("Stairway To Heaven", "Led Zeppelin", "IV", 1971, ["Rock"]),
    ("Whole Lotta Love", "Led Zeppelin", "Led Zeppelin II", 1969, ["Rock", "Hard Rock", "Blues Rock"]),
    ("Hallelujah", "Leonard Cohen", "Various Positions", 1984, ["Folk", "Rock"]),
    ("Like a Prayer", "Madonna", "Like a Prayer", 1989, ["Pop"]),
    ("Somewhere I Belong", "Linkin Park", "Meteora", 2003, ["Rock", "Alternative Rock", "Nu Metal"]),
    ("Little Red Corvette", "Prince", "1999", 1982, ["Pop", "R&B", "Funk"]),
    ("Live Forever", "Oasis", "Definitely Maybe", 1994, ["Rock", "Britpop"]),
    ("Lose Yourself", "Eminem", "8 Mile", 2002, ["Hip Hop"]),
    ("Free Bird", "Lynyrd Skynyrd", "(Pronounced 'Lěh-'nérd 'Skin-'nérd)", 1973, ["Rock", "Southern Rock"]),
    ("Man in the Mirror", "Michael Jackson", "Bad", 1987, ["Pop", "Soul"]),
    ("Uptown Funk", "Mark Ronson ft. Bruno Mars", "Uptown Special", 2014, ["Funk", "Pop", "R&B"]),
    ("What's Going On", "Marvin Gaye", "What's Going On", 1971, ["R&B", "Soul"]),
    ("Material Girl", "Madonna", "Like a Virgin", 1984, ["Pop"]),
    ("Boléro", "Maurice Ravel", "Boléro", 1928, ["Classical", "Orchestral"]),
    ("Message In A Bottle", "The Police", "Reggatta de Blanc", 1979, ["Rock", "Reggae"]),
    ("Smooth Criminal", "Michael Jackson", "Bad", 1987, ["Pop", "R&B"]),
    ("All Blues", "Miles Davis", "Kind of Blue", 1959, ["Jazz", "Modal Jazz"]),
    ("Blue In Green", "Miles Davis", "Kind of Blue", 1959, ["Jazz", "Modal Jazz"]),
    ("Freddie Freeloader", "Miles Davis", "Kind of Blue", 1959, ["Jazz", "Modal Jazz"]),
    ("So What", "Miles Davis", "Kind of Blue", 1959, ["Jazz", "Modal Jazz"]),
    ("Moonlight Sonata", "Ludwig van Beethoven", "Piano Sonata No. 14", 1801, ["Classical"]),
    ("Mr. Brightside", "The Killers", "Hot Fuss", 2004, ["Rock", "Indie Rock"]),
    ("Ms. Jackson", "Outkast", "Stankonia", 2000, ["Hip Hop", "R&B"]),
    ("Blue Monday", "New Order", "Movement", 1981, ["Synth-pop", "New Wave", "Dance"]),
    ("Nice For What", "Drake", "Scorpion", 2018, ["Hip Hop", "Bounce"]),
    ("Heart-Shaped Box", "Nirvana", "In Utero", 1993, ["Rock", "Grunge"]),
    ("In Bloom", "Nirvana", "Nevermind", 1991, ["Rock", "Grunge"]),
    ("Lithium", "Nirvana", "Nevermind", 1991, ["Rock", "Grunge"]),
    ("No Woman, No Cry", "Bob Marley & The Wailers", "Natty Dread", 1974, ["Reggae"]),
    ("Numb", "Linkin Park", "Meteora", 2003, ["Rock", "Alternative Rock", "Nu Metal"]),
    ("Ode to Joy", "Ludwig van Beethoven", "Symphony No. 9", 1824, ["Classical", "Symphony"]),
    ("One Dance", "Drake ft. Wizkid & Kyla", "Views", 2016, ["Hip Hop", "Dancehall"]),
    ("One", "U2", "Achtung Baby", 1991, ["Rock"]),
    ("Oops!... I Did It Again", "Britney Spears", "Oops!... I Did It Again", 2000, ["Pop"]),
    ("Roses", "Outkast", "Speakerboxxx/The Love Below", 2003, ["Hip Hop", "Funk", "Soul"]),
    ("Papa Don't Preach", "Madonna", "True Blue", 1986, ["Pop"]),
    ("Personal Jesus", "Depeche Mode", "Violator", 1989, ["Synth-pop", "Electronic"]),
    ("Happy", "Pharrell Williams", "G I R L", 2013, ["Pop", "Funk", "Soul"]),
    ("Pride (In The Name Of Love)", "U2", "The Unforgettable Fire", 1984, ["Rock"]),
    ("Kiss", "Prince", "Parade", 1986, ["Funk", "Pop"]),
    ("Nessun Dorma", "Giacomo Puccini", "Turandot", 1926, ["Classical", "Opera"]),
    ("Purple Rain", "Prince", "Purple Rain", 1984, ["Pop", "R&B", "Funk", "Rock"]),
    ("Another One Bites The Dust", "Queen", "The Game", 1980, ["Rock", "Funk"]),
    ("Don't Stop Me Now", "Queen", "Jazz", 1988, ["Rock", "Pop"]),
    ("Killer Queen", "Queen", "Sheer Heart Attack", 1974, ["Rock", "Pop"]),
    ("Radio Ga Ga", "Queen", "The Works", 1984, ["Rock", "Synth-pop"]),
    ("Somebody To Love", "Queen", "A Day at the Races", 1976, ["Rock"]),
    ("We Will Rock You", "Queen", "News of the World", 1977, ["Rock"]),
    ("Bohemian Rhapsody", "Queen", "A Night at the Opera", 1975, ["Rock", "Pop"]),
    ("We Are The Champions", "Queen", "News of the World", 1977, ["Rock"]),
    ("Hallelujah I Love Her So", "Ray Charles", "Ray Charles", 1957, ["R&B", "Soul"]),
    ("Hit the Road Jack", "Ray Charles", "Ray Charles and Betty Carter", 1961, ["R&B"]),
    ("I Got a Woman", "Ray Charles", "Ray Charles", 1957, ["R&B", "Soul", "Gospel"]),
    ("What'd I Say", "Ray Charles", "What'd I Say", 1959, ["R&B", "Rock and Roll", "Soul"]),
    ("Californication", "Red Hot Chili Peppers", "Californication", 1999, ["Rock", "Funk Rock", "Alternative Rock"]),
    ("Otherside", "Red Hot Chili Peppers", "Californication", 1999, ["Rock", "Alternative Rock"]),
    ("Scar Tissue", "Red Hot Chili Peppers", "Californication", 1999, ["Rock", "Funk Rock", "Alternative Rock"]),
    ("Under the Bridge", "Red Hot Chili Peppers", "Blood Sugar Sex Magik", 1991, ["Rock", "Alternative Rock"]),
    ("Can't Stop", "Red Hot Chili Peppers", "By the Way", 2002, ["Rock", "Funk Rock", "Alternative Rock"]),
    ("Ride of the Valkyries", "Richard Wagner", "Die Walküre", 1856, ["Classical", "Opera"]),
    ("God Save the Queen", "Sex Pistols", "Never Mind the Bollocks, Here's the Sex Pistols", 1977, ["Punk Rock"]),
    ("Shallow", "Lady Gaga and Bradley Cooper", "A Star Is Born", 2018, ["Pop", "Rock", "Country"]),
    ("So Fresh, So Clean", "Outkast", "Stankonia", 2000, ["Hip Hop", "Funk"]),
    ("Tainted Love", "Soft Cell", "Non-Stop Erotic Cabaret", 1981, ["Synth-pop"]),
    ("Stay on These Roads", "a-ha", "Stay on These Roads", 1988, ["Pop"]),
    ("Sunday Bloody Sunday", "U2", "War", 1983, ["Rock"]),
    ("Sweet Dreams (Are Made of This)", "Eurythmics", "Sweet Dreams (Are Made of This)", 1983, ["Synth-pop", "New Wave"]),
    ("Take Me Out", "Franz Ferdinand", "Franz Ferdinand", 2004, ["Rock", "Indie Rock"]),
    ("Take on Me", "a-ha", "Hunting High and Low", 1985, ["Synth-pop", "New Wave"]),
    ("The Blacker The Berry", "Kendrick Lamar", "To Pimp a Butterfly", 2015, ["Hip Hop", "Jazz Rap"]),
    ("Bohemian Like You", "The Dandy Warhols", "Thirteen Tales from Urban Bohemia", 2000, ["Rock", "Indie Rock"]),
    ("The Masterplan", "Oasis", "The Masterplan", 1998, ["Rock", "Britpop"]),
    ("Roxanne", "The Police", "Outlandos d'Amour", 1978, ["Rock", "New Wave"]),
    ("The Real Slim Shady", "Eminem", "The Marshall Mathers LP", 2000, ["Hip Hop"]),
    ("The Show Must Go On", "Queen", "Innuendo", 1991, ["Rock"]),
    ("Juicebox", "The Strokes", "First Impressions of Earth", 2005, ["Rock", "Indie Rock"]),
    ("Last Nite", "The Strokes", "Is This It", 2001, ["Rock", "Indie Rock"]),
    ("Reptilia", "The Strokes", "Room on Fire", 2003, ["Rock", "Indie Rock"]),
    ("The Sun Always Shines on TV", "a-ha", "Hunting High and Low", 1985, ["Synth-pop"]),
    ("Blinding Lights", "The Weeknd", "After Hours", 2019, ["Pop", "Synth-pop", "R&B"]),
    ("Seven Nation Army", "The White Stripes", "Elephant", 2003, ["Rock", "Alternative Rock"]),
    ("There Must Be An Angel (Playing With My Heart)", "Eurythmics", "Be Yourself Tonight", 1985, ["Synth-pop"]),
    ("Thriller", "Michael Jackson", "Thriller", 1982, ["Pop", "R&B", "Funk"]),
    ("Till I Collapse", "Eminem ft. Nate Dogg", "The Eminem Show", 2002, ["Hip Hop"]),
    ("Toxic", "Britney Spears", "In the Zone", 2003, ["Pop", "Dance"]),
    ("With Or Without You", "U2", "The Joshua Tree", 1987, ["Rock"]),
    ("Walking On The Moon", "The Police", "Reggatta de Blanc", 1979, ["Rock", "Reggae"]),
    ("When Doves Cry", "Prince", "Purple Rain", 1984, ["Pop", "Funk"]),
    ("I Will Always Love You", "Whitney Houston", "The Bodyguard", 1992, ["R&B", "Pop", "Soul"]),
    ("Womanizer", "Britney Spears", "Circus", 2008, ["Pop", "Dance"]),
    ("Wonderwall", "Oasis", "(What's the Story) Morning Glory?", 1995, ["Rock", "Britpop"]),
    ("Would I Lie to You?", "Eurythmics", "Be Yourself Tonight", 1985, ["Pop", "Rock", "Soul"]),
    ("Yesterday", "The Beatles", "Help!", 1965, ["Pop"]),
    ("Кукла Колдуна", "Король и Шут", "Кукла Колдуна", 2001, ["Rock", "Punk"]),
    ("Что такое осень", "ДДТ", "Что такое осень", 1991, ["Rock", "Folk"]),
    ("Морячка", "Олег Газманов", "Морячка", 1991, ["Pop", "Rock"]),
    ("Есаул", "Олег Газманов", "Есаул", 1991, ["Pop", "Rock"]),
    ("Есаул", "Олег Газманов", "Есаул", 1991, ["Pop", "Rock"])
]



conn = psycopg2.connect(
                host=config.config_db["host"],
                database=config.config_db["dbname"],
                user=config.config_db["user"],
                password=config.config_db["password"]
)



for i in range(len(songs)):
    try:
        path = f"sources\\songs\\{songs[i]}"
        features = extract_features(path).tolist()
        lyrics = text_par(songs_with_info[i][0])
        with conn.cursor() as cursor:
            cursor.execute("""
                INSERT INTO tracks (
                    song,
                    name,
                    lyrics, 
                    features
                )
                VALUES (%s, %s, %s, %s)
            """, (
                path,
                songs[i],
                lyrics,
                features
            ))
            print(f"песня {songs[i]} загружена в бд")

            conn.commit()

    except Exception as e:
        print(f"песня {songs[i]} не сохранилась. \nОшибка:{e}")
    finally:
        cursor.close()

